backend:
  # name: git-gateway
  name: github
  repo: Landlord-Tech/landlord-tech-landing-page
  branch: dev

#publish_mode: editorial_workflow
# site_url: https://calculator.ourpetpolicy.com/

media_folder: static/assets
public_folder: /assets

collections:
  - name: homepage
    label: homepage
    folder: src/markdown/homepage
    preview_path: /
    create: true
    editor:
      preview: false
    fields:
      - { name: title, label: Title }
      - { name: metaTitle, label: Meta Title }
      - { name: metaDescription, label: Meta Description, widget: text }
      - { name: heroHeading, label: Hero Heading }
      - { name: heroText, label: Hero Text }
      - { name: heroBtn, label: Hero button }
      - { name: heroBtnUrl, label: Hero button url }
      - { name: heroImg, label: Hero image, widget: image }
