backend:
  name: git-gateway
#  name: gitlab
#  repo: ourpetpolicy/our-pet-policy-landing-page

#publish_mode: editorial_workflow
site_url: https://calculator.ourpetpolicy.com/

media_folder: static/assets
public_folder: /assets
